[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ru-pl-speech-translation"
version = "0.3.0"
description = "Skeleton for RU->PL speech translation course project."
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[project.scripts]
ru-pl-st = "ru_pl_st.cli:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
